name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install dependencies
        run: shards install
      - name: Build binding
        run: make binding
      - name: Run specs
        run: crystal spec
      - name: Lint
        uses: crystal-ameba/github-action@master
